/-
Copyright (c) 2026 Provable Inc.
Licensed under the Apache License, Version 2.0; see LICENSE.md for details.
-/

import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.LinearAlgebra.Lagrange
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots
import Varuna.R1CS

/-!
# Evaluation domains, vanishing polynomials, and Schwartz–Zippel

snarkVM’s `EvaluationDomain` is a multiplicative subgroup of size `2^k`
inside an FFT-friendly field. The vanishing polynomial on that domain is
`v_H(X) = X^{ | H | } - 1`. Every later PIOP identity quotes :

* `v_H(α) = 0` if and only if `α ∈ H`
* a nonzero polynomial of degree `d` has at most `d` roots (the
  univariate Schwartz–Zippel bound used to size `szBadSet`)
* Lagrange basis polynomials that pick out a single domain node

This module is iteration 1. Extractors later treat a challenge that lands
in `szBadSet p` as computed break data, not as an existential in `Prop`.
-/

open Polynomial

namespace Varuna

variable {F : Type*} [Field F]

/-- Our inductive `PowTwo` is Mathlib/core `Nat.isPowerOfTwo`. -/
theorem PowTwo.iff_isPowerOfTwo {n : Nat} : PowTwo n ↔ n.isPowerOfTwo := by
  constructor
  · intro h
    induction h with
    | one => exact Nat.isPowerOfTwo_one
    | twice _ ih =>
      simpa [Nat.mul_comm] using Nat.isPowerOfTwo_mul_two_of_isPowerOfTwo ih
  · rintro ⟨k, rfl⟩
    induction k with
    | zero =>
      simpa using PowTwo.one
    | succ k ih =>
      rw [Nat.pow_succ, Nat.mul_comm]
      exact PowTwo.twice ih

/-- Formatted public-input length is a power of two in the core sense. -/
theorem formattedPublicInputAdmissible_isPowerOfTwo (input : List Int)
    (h : formattedPublicInputAdmissible input) : input.length.isPowerOfTwo :=
  (PowTwo.iff_isPowerOfTwo).1 h

/-- Smallest power of two that is at least `numCoeffs`. Matches `EvaluationDomain::new`. -/
def domainSize (numCoeffs : Nat) : Nat :=
  Nat.nextPowerOfTwo numCoeffs

/-- `domainSize` is always a power of two. -/
theorem domainSize_isPowerOfTwo (numCoeffs : Nat) :
    (domainSize numCoeffs).isPowerOfTwo :=
  Nat.isPowerOfTwo_nextPowerOfTwo numCoeffs

/-- Multiplicative subgroup of order `n = 2^k`, generated by a primitive `n`-th root. -/
structure EvalDomain (F : Type*) [Field F] where
  /-- Domain size; a power of two (snarkVM `size`). -/
  n : Nat
  /-- `n` is a positive power of two. -/
  hn : PowTwo n
  /-- Primitive `n`-th root of unity (snarkVM `group_gen`). -/
  ω : F
  /-- `ω` has multiplicative order `n`. -/
  hω : IsPrimitiveRoot ω n

namespace EvalDomain

variable (H : EvalDomain F)

/-- Domain size is positive. -/
theorem n_pos : 0 < H.n :=
  PowTwo.pos H.hn

/-- Domain size is a nonzero natural, so `n`-th roots are well-defined. -/
instance : NeZero H.n :=
  ⟨H.n_pos.ne'⟩

/-- Domain size as a field element (snarkVM `size_as_field_element`). -/
def sizeAsField : F :=
  H.n

/-- `n` is invertible in `F` because a primitive `n`-th root exists. -/
theorem n_ne_zero : (H.n : F) ≠ 0 :=
  (IsPrimitiveRoot.neZero' H.hω).out

/-- Inverse of the domain size (snarkVM `size_inv`). -/
def sizeInv : F :=
  (H.n : F)⁻¹

/-- The size and its inverse multiply to one. -/
theorem mul_sizeInv : H.sizeAsField * H.sizeInv = 1 := by
  unfold sizeAsField sizeInv
  exact mul_inv_cancel₀ H.n_ne_zero

/-- Inverse of the group generator (snarkVM `group_gen_inv`). -/
def groupGenInv : F :=
  H.ω⁻¹

/-- The generator is nonzero, as it is a root of unity of positive order. -/
theorem ω_ne_zero : H.ω ≠ 0 :=
  H.hω.ne_zero H.n_pos.ne'

/-- The generator times its inverse is one. -/
theorem mul_groupGenInv : H.ω * H.groupGenInv = 1 :=
  mul_inv_cancel₀ H.ω_ne_zero

/-- The set of domain elements `{ ω^i | i < n }` (snarkVM `elements`). -/
noncomputable def elements : Finset F :=
  nthRootsFinset H.n (1 : F)

/-- Membership in the domain is the equation `α^n = 1`. -/
theorem mem_elements_iff {α : F} : α ∈ H.elements ↔ α ^ H.n = 1 :=
  mem_nthRootsFinset H.n_pos (1 : F)

/-- Every power of the generator lies in the domain. -/
theorem ω_pow_mem (i : Nat) : H.ω ^ i ∈ H.elements := by
  rw [mem_elements_iff, ← pow_mul, mul_comm, pow_mul, H.hω.pow_eq_one, one_pow]

/-- Membership in the domain is equivalent to being a power of the generator. -/
theorem mem_elements_iff_pow {α : F} :
    α ∈ H.elements ↔ ∃ i < H.n, H.ω ^ i = α := by
  constructor
  · intro hα
    obtain ⟨i, hi, rfl⟩ := H.hω.eq_pow_of_pow_eq_one ((mem_elements_iff H).1 hα)
    exact ⟨i, hi, rfl⟩
  · rintro ⟨i, _, rfl⟩
    exact H.ω_pow_mem i

/-- The domain has cardinality `n`. -/
theorem card_elements : H.elements.card = H.n :=
  H.hω.card_nthRootsFinset

/-- Index set `{0, …, n-1}` used to label domain nodes. -/
def indexSet : Finset Nat :=
  Finset.range H.n

/-- The `i`-th domain node `ω^i`. -/
def node (i : Nat) : F :=
  H.ω ^ i

/-- Distinct indices below `n` give distinct nodes. -/
theorem injOn_node : Set.InjOn H.node H.indexSet := by
  intro i hi j hj hij
  exact H.hω.pow_inj (Finset.mem_range.mp hi) (Finset.mem_range.mp hj) hij

/-- Vanishing polynomial `v_H(X) = X^n - 1`. Matches snarkVM `vanishing_polynomial`. -/
noncomputable def vanishing : F[X] :=
  X ^ H.n - C 1

/-- Evaluating `v_H` at `α` is `α^n - 1`. -/
theorem vanishing_eval (α : F) : H.vanishing.eval α = α ^ H.n - 1 := by
  simp [vanishing]

/-- `v_H` is not the zero polynomial. -/
theorem vanishing_ne_zero : H.vanishing ≠ 0 :=
  X_pow_sub_C_ne_zero H.n_pos (1 : F)

/-- The degree of `v_H` is the domain size. -/
theorem natDegree_vanishing : H.vanishing.natDegree = H.n :=
  natDegree_X_pow_sub_C

/-- `v_H(α) = 0` if and only if `α` lies in the domain. -/
theorem vanishing_eq_zero_iff (α : F) : H.vanishing.eval α = 0 ↔ α ∈ H.elements := by
  rw [vanishing_eval, sub_eq_zero, mem_elements_iff]

/-- Lagrange basis polynomial for node `i` (1 at `ω^i`, 0 at the other nodes). -/
noncomputable def lagrange (i : Nat) : F[X] :=
  Lagrange.basis H.indexSet H.node i

/-- The `i`-th Lagrange polynomial evaluates to `1` at `ω^i`. -/
theorem eval_lagrange_self {i : Nat} (hi : i < H.n) :
    (H.lagrange i).eval (H.node i) = 1 :=
  Lagrange.eval_basis_self H.injOn_node (Finset.mem_range.mpr hi)

/-- The `i`-th Lagrange polynomial evaluates to `0` at a different node. -/
theorem eval_lagrange_of_ne {i j : Nat} (hij : i ≠ j) (hj : j < H.n) :
    (H.lagrange i).eval (H.node j) = 0 :=
  Lagrange.eval_basis_of_ne hij (Finset.mem_range.mpr hj)

end EvalDomain

/-- Univariate Schwartz–Zippel: a polynomial has at most `natDegree` roots. -/
theorem schwartzZippel_card (p : F[X]) : Multiset.card p.roots ≤ p.natDegree :=
  p.card_roots'

/-- Challenges that make a nonzero residual vanish. Cardinality is at most the degree. -/
noncomputable def szBadSet [DecidableEq F] (p : F[X]) : Finset F :=
  p.roots.toFinset

/-- The Schwartz–Zippel bad set is no larger than the polynomial’s degree. -/
theorem card_szBadSet_le_natDegree [DecidableEq F] (p : F[X]) :
    (szBadSet p).card ≤ p.natDegree :=
  (Multiset.toFinset_card_le _).trans (schwartzZippel_card p)

/-- A point outside the bad set is not a root of a nonzero polynomial. -/
theorem eval_ne_zero_of_notMem_szBadSet [DecidableEq F] {p : F[X]} {α : F}
    (hp : p ≠ 0) (hα : α ∉ szBadSet p) : p.eval α ≠ 0 := by
  intro h
  exact hα (Multiset.mem_toFinset.2 ((mem_roots hp).2 h))

end Varuna