/-
Copyright (c) 2026 Provable Inc.
Licensed under the Apache License, Version 2.0; see LICENSE.md for details.
-/

import Varuna.AxiomCheck
import Varuna.SonicPC
import Varuna.FiatShamir
import Varuna.Batching
import Varuna.Match
import Varuna.Soundness
import Varuna.SpotCheck

/-!
# Trust boundary (iterations 0–8 + snarkVM samples)

Ironwood keeps the trusted base of every advertised endpoint as a
build-time check. `assert_axioms` fails the build if a named theorem
depends on `sorryAx` or any axiom outside `propext` / `Classical.choice` /
`Quot.sound`. `assert_computable` additionally requires a `def` that is
not `noncomputable` and forbids `Classical.choice` on the data path.
-/

open Varuna.AxiomCheck

assert_axioms Varuna.satisfies_nil
assert_axioms Varuna.satisfies_append
assert_axioms Varuna.mulConstraint_holds_iff
assert_axioms Varuna.hadamardSat_zero
assert_axioms Varuna.satisfies_iff_hadamard
assert_axioms Varuna.unformat_formatPublicInput
assert_axioms Varuna.assignmentOf_format_zero
assert_axioms Varuna.formatPublicInput_nil_admissible
assert_axioms Varuna.toy_mul_holds
assert_axioms Varuna.formatted_toy_holds
assert_axioms Varuna.formatted_toy_iff
assert_axioms Varuna.EvalDomain.vanishing_eq_zero_iff
assert_axioms Varuna.schwartzZippel_card
assert_axioms Varuna.card_szBadSet_le_natDegree
assert_axioms Varuna.eval_ne_zero_of_notMem_szBadSet
assert_axioms Varuna.EvalDomain.eval_lagrange_self
assert_axioms Varuna.EvalDomain.eval_interpolate
assert_axioms Varuna.holographicEval_at_nodes
assert_axioms Varuna.rowOracle_eval
assert_axioms Varuna.colOracle_eval
assert_axioms Varuna.valOracle_eval
assert_axioms Varuna.matrixAt
assert_computable Varuna.CircuitInfo.maxNonZero
assert_axioms Varuna.EvalDomain.vanishing_dvd_of_eval_eq_zero
assert_axioms Varuna.EvalDomain.sum_eval_of_natDegree_lt
assert_axioms Varuna.inspectResidual_accepts
assert_axioms Varuna.rowcheck_on_domain
assert_axioms Varuna.rowcheckResidual_honest
assert_axioms Varuna.rowcheck_extract
assert_axioms Varuna.univariateResidual_honest
assert_axioms Varuna.univariate_sum
assert_axioms Varuna.honestUnivariate_sum
assert_axioms Varuna.univariate_extract
assert_axioms Varuna.matrix_on_domain
assert_axioms Varuna.matrix_rational
assert_axioms Varuna.matrixResidual_honest
assert_axioms Varuna.matrix_extract
assert_axioms Varuna.accepts_of_residuals_zero
assert_computable Varuna.lcWithZeroEval
assert_axioms Varuna.LinearCombination.eval_add
assert_axioms Varuna.kzgCheck_honest
assert_axioms Varuna.pairingBreak_of_double_opening
assert_axioms Varuna.inspectBinding_of_double_check
assert_axioms Varuna.kzgCheck_batch
assert_computable Varuna.LinearCombination.empty
assert_axioms Varuna.challenge_eq_ro
assert_axioms Varuna.alpha_prefix_isPrefix
assert_axioms Varuna.alpha_prefix_isPrefix_beta
assert_axioms Varuna.challenge_of_same_prefix
assert_axioms Varuna.inspectFork_some
assert_axioms Varuna.inspectFork_distinct
assert_axioms Varuna.inspectCollision_some
assert_axioms Varuna.inspectCollision_ne
assert_axioms Varuna.v2_secondRound_lt_v1
assert_axioms Varuna.hasPrepareThird_V2
assert_axioms Varuna.before_length
assert_computable Varuna.inspectFork
assert_computable Varuna.inspectCollision
assert_computable Varuna.squeezeN
assert_axioms Varuna.circuitCombiners_head
assert_axioms Varuna.etaA_eq_one
assert_axioms Varuna.inspectBatch_accepts
assert_axioms Varuna.inspectBatch_some
assert_axioms Varuna.nested_domain_card_dvd
assert_axioms Varuna.selector_mul_vanishing
assert_axioms Varuna.lift_residual
assert_axioms Varuna.batched_rowcheck_two
assert_axioms Varuna.alpha_independent_of_prepareThird
assert_axioms Varuna.prepareThird_challenge_eq
assert_axioms Varuna.extraRound_iff_V2
assert_computable Varuna.inspectBatch
assert_computable Varuna.weightedSum
assert_axioms Varuna.lcNames_match_snarkVM
assert_axioms Varuna.typedAHPAccepts_iff
assert_axioms Varuna.typedBatchAccepts_iff
assert_axioms Varuna.toy_ahp_accepts
assert_axioms Varuna.toy_ahp_rejects_flip_rowcheck
assert_axioms Varuna.toy_ahp_rejects_flip_lineval
assert_axioms Varuna.toy_ahp_rejects_flip_matrix
assert_axioms Varuna.toy_batch_lucky
assert_axioms Varuna.toy_typed_proof_accepts
assert_axioms Varuna.toy_typed_proof_rejects_flip
assert_axioms Varuna.toy_kzg_accepts
assert_axioms Varuna.toy_binding_break
assert_computable Varuna.typedAHPAccepts
assert_computable Varuna.modellingFloors
assert_axioms Varuna.inspectAHP_none
assert_axioms Varuna.inspectAHP_eq_none_implies
assert_axioms Varuna.inspectBinding_none_same_point
assert_axioms Varuna.knowledgeSoundness
assert_axioms Varuna.knowledgeSoundness_toy_typed
assert_axioms Varuna.knowledgeSoundness_rests_on_floors
assert_computable Varuna.snarkVMPin
assert_axioms Varuna.snarkVMPin_length
assert_axioms Varuna.sample_lcWithZeroEval
assert_axioms Varuna.sample_v2_second_round_squeeze
assert_axioms Varuna.sample_prepareThird_eta_squeezes
assert_axioms Varuna.sample_first_circuit_combiner
assert_axioms Varuna.sample_etaA_is_one
assert_axioms Varuna.EvalDomain.node_zero
assert_axioms Varuna.sample_padEntry_indices
assert_axioms Varuna.selectorPoly_eval
assert_axioms Varuna.sample_selector_self
assert_axioms Varuna.matrixBPoly_four_terms
assert_axioms Varuna.sample_kzg_equation
assert_axioms Varuna.sample_toy_vanishing_at_one
assert_axioms Varuna.sample_toy_size_ratio
assert_computable Varuna.queryChallengeNames